version: 2

defaults: &defaults
  working_directory: ~/code
  docker:
  - image: circleci/android:api-28
  environment:
    JVM_OPTS: -Xmx3200m

jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Run Tests
        command: ./gradlew lint test
    - store_artifacts:
        path: app/build/reports
        destination: reports
    - store_test_results:
        path: app/build/test-results

  deploy_debug:
    <<: *defaults
    steps:
    - run:
        name: Run Assemble Debug
        command: ./gradlew assembleDebug
    - run: |
        GIT_HASH=$(git rev-parse --short HEAD)
        GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        curl \
        -F "token=DEPLOY_GATE_API_KEY" \
        -F "file=@app/build/outputs/apk/debug/app-debug.apk" \
        -F "message=git:$GIT_HASH" \
        -F "distribution_name=$GIT_BRANCH" \
        https://deploygate.com/api/users/kgmyshin/apps


workflows:
  version: 2
  build:
    jobs:
    - build
    - deploy_debug:
        requires:
        - build
        filters:
          branches:
            only: master
